Verify Results [IGP - 0006] IOTA Rebased Governance Proposal] and correct some file endings
iota-community/governance-participation-events pull request #15
Opened 2024-12-17 06:53 UTC by dlt-green

# Welcome Community Node operators

We want to verify the outcome of the recently ended Governance vote event.

To do this, we need the help of our community node operators, who tracked this event.
 
## **Please follow the next steps:**

### Event [IGP - 0006] - IOTA Rebased Governance Proposal] and correct some file endings- **IOTA HORNET**

- Open a new tab in your browser.
   - If your **IOTA Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0xa6ce50bc0e83952b2f21fc373fe4d7030a5ea2d3b97ff48788d709bf4210261a/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0xa6ce50bc0e83952b2f21fc373fe4d7030a5ea2d3b97ff48788d709bf4210261a/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare the following checksum

 Check that the status of the event is "**ended**"
 

### **Now compare all checksums of your node's event data with the following ones:**

- Event [IGP - 0006]: `0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16`

## **Leave an approving review on this Pull request or comment "approve" If your checksums in this event matches. You can also add screenshots/proofs of your events in the comments to this PR.**

Thank you for contributing!

2024-12-17 06:53 UTC, dlt-green reviewed
![image](https://github.com/user-attachments/assets/99fb53e6-9e04-44ee-a74d-a7502cfc34dc)

2024-12-17 07:54 UTC, Phyloiota approved these changes
Checksum: 0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16

Approved

2024-12-17 08:36 UTC, cbries commented
![image](https://github.com/user-attachments/assets/acb11b22-3f30-4046-a16c-40fa3dc3a864)


Checksum: 0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16

Approved

2024-12-17 08:47 UTC, o-l-i-v-e-r commented
![image](https://github.com/user-attachments/assets/bb0a8689-1344-4f3f-b932-8a9b24431beb)

2024-12-17 09:07 UTC, 0xKtota commented
Approved✅
Event ID: 0xa6ce50bc0e83952b2f21fc373fe4d7030a5ea2d3b97ff48788d709bf4210261a
Checksum: 0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16

2024-12-17 10:32 UTC, DerAnhalter commented
![Screenshot-hornet-participation](https://github.com/user-attachments/assets/bb6704f0-7a02-49c2-aef5-0aac3e562a01)

2024-12-17 11:14 UTC, no8ody approved these changes
lgtm

checksum: `0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16`

2024-12-17 13:02 UTC, alexsporn commented
✅ 
```
{
  "milestoneIndex": 14718422,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 269872084868,
          "accumulated": 31647575919696580
        },
        {
          "value": 2,
          "current": 4244546210,
          "accumulated": 474777288656110
        },
        {
          "value": 0,
          "current": 426324954,
          "accumulated": 48806799459141
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16"
}
```

2024-12-17 13:09 UTC, shufps commented
✅
```
{
  "milestoneIndex": 14718422,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 269872084868,
          "accumulated": 31647575919696580
        },
        {
          "value": 2,
          "current": 4244546210,
          "accumulated": 474777288656110
        },
        {
          "value": 0,
          "current": 426324954,
          "accumulated": 48806799459141
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16"
}
```

2024-12-17 14:45 UTC, johanneskeim commented
Checksum: 0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16
Approved ✅

2024-12-17 22:11 UTC, mag-node reviewed
![event](https://github.com/user-attachments/assets/6fba9fab-d14b-4260-9997-f3c5be6b478c)

2024-12-18 13:18 UTC, TeeVeeEss commented
My internal node url http://192.168.50.142:9000/api/participation/v1/events/0xa6ce50bc0e83952b2f21fc373fe4d7030a5ea2d3b97ff48788d709bf4210261a/status gives:
```json
{
  "milestoneIndex": 14718422,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 269872084868,
          "accumulated": 31647575919696580
        },
        {
          "value": 2,
          "current": 4244546210,
          "accumulated": 474777288656110
        },
        {
          "value": 0,
          "current": 426324954,
          "accumulated": 48806799459141
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16"
}
```
Approved

2024-12-19 09:15 UTC, Dr-Electron requested changes

2024-12-19 09:15 UTC, Dr-Electron commented on results/vote/[IGP - 0006] IOTA Rebased Governance Proposal.json
> +]
Half of the resulting json is missing here.

```suggestion
{
  "milestoneIndex": 14718422,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 269872084868,
          "accumulated": 31647575919696580
        },
        {
          "value": 2,
          "current": 4244546210,
          "accumulated": 474777288656110
        },
        {
          "value": 0,
          "current": 426324954,
          "accumulated": 48806799459141
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x2792799bc62a0ff56624e0fabde28db0301b872b53ce4e153d32cd619a939e16"
}
```

2024-12-19 10:02 UTC, Dr-Electron approved these changes

2025-01-13 00:00 UTC, merged